CREATE OR REPLACE PROCEDURE SOP_EXTRACT AS

BEGIN
insert into case_info
  (case_id,
   case_no,
   case_name,
   case_status,
   case_type,
   case_date,
   case_desc,
   incident_place,
   incident_date,
   INCIDENT_DATE_BEGIN,
   INCIDENT_DATE_END,
   punish_date,
   handle_unit,
   handle_people,
   handle_people_id,
   accept_date,
   accept_unit,
   undertake_unit,
   undertake_area,
   undertake_area_id,
   call_no,
   criminal_name,
   case_type_imp,
   jq_no,
   lat_x,
   lon_y,
   MODIFTIME)
  select a.id,
         a.Ajbh,
         a.ajmc,
         a.ajzt,
         b.aybh,
         a.lasj,
         a.jyaq,
         a.fadd,
         a.fasj,
         a.lasj,
         a.jasj,
         a.cfsj,
         a.zbdwjz,
         a.ZBR_XM,
         a.ZBR_SFZH,
         a.slsj,
         a.SLDW_BH,
         a.CBDW_BH,
         a.CBQY_JC,
         a.CBQY_BH,
         a.jqbh,
         a.XYR_XM,
         a.ajlx,
         a.jqbh,
         a.zbx,
         a.zby,
         a.xgsj
    from (select *
            from (select aj.*,
                         row_number() over(partition by aj.ajbh order by aj.xgsj desc) ajlasted
                    from MID.ZFBH_CASE_GG_ajxx@zfbh_sop aj
                   where aj.isdel = '0')
           where ajlasted = 1) a,
         (select aybh, ajbh
            from (select t.ajbh,
                         t.aybh,
                         row_number() over(partition by t.ajbh order by t.xgsj desc) aylasted
                    from MID.ZFBH_CASE_GG_AJAB@zfbh_sop t
                   where t.isdel = '0')
           where aylasted = 1) b
   where a.ajbh = b.ajbh(+)
     and not exists
   (select 1 from case_info i where a.ajbh = i.case_no);

commit;
-- update
MERGE INTO CASE_INFO i
using (select a.id,
              a.Ajbh,
              a.ajmc,
              a.ajzt,
              b.aybh,
              a.lasj,
              a.jyaq,
              a.fadd,
              a.fasj,
              a.jasj,
              a.cfsj,
              a.zbdwjz,
              a.ZBR_XM,
              a.ZBR_SFZH,
              a.slsj,
              a.SLDW_BH,
              a.CBDW_BH,
              a.CBQY_JC,
              a.CBQY_BH,
              a.XYR_XM,
              a.ajlx,
              a.jqbh,
              a.zbx,
              a.zby,
              a.xgsj
         from (select *
                 from (select aj.*,
                              row_number() over(partition by aj.ajbh order by aj.xgsj desc) ajlasted
                         from MID.ZFBH_CASE_GG_ajxx@zfbh_sop aj
                        where aj.isdel = '0')
                where ajlasted = 1) a,
              (select aybh, ajbh
                 from (select t.ajbh,
                              t.aybh,
                              row_number() over(partition by t.ajbh order by t.xgsj desc) aylasted
                         from MID.ZFBH_CASE_GG_AJAB@zfbh_sop t
                        where t.isdel = '0')
                where aylasted = 1) b
        where a.ajbh = b.ajbh(+)) p
on (p.ajbh = i.case_no)
WHEN MATCHED THEN
  update
     set i.case_name           = p.ajmc,
         i.case_status         = p.ajzt,
         i.case_type           = p.aybh,
         i.case_date           = p.lasj,
         i.case_desc           = p.jyaq,
         i.incident_place      = p.fadd,
         i.incident_date       = p.fasj,
         i.INCIDENT_DATE_BEGIN = p.lasj,
         i.INCIDENT_DATE_END   = p.jasj,
         i.punish_date         = p.cfsj,
         i.handle_unit         = p.zbdwjz,
         i.handle_people       = p.ZBR_XM,
         i.handle_people_id    = p.ZBR_SFZH,
         i.accept_date         = p.slsj,
         i.accept_unit         = p.SLDW_BH,
         i.undertake_unit      = p.CBDW_BH,
         i.undertake_area      = p.CBQY_JC,
         i.undertake_area_id   = p.CBQY_BH,
         i.call_no             = p.jqbh,
         i.criminal_name       = p.XYR_XM,
         i.case_type_imp       = p.ajlx,
         i.jq_no               = p.jqbh,
         i.lat_x               = p.zbx,
         i.lon_y               = p.zby,
         i.modiftime           = p.xgsj
   where p.xgsj > i.modiftime;
commit;

MERGE INTO sop_lajds k
USING (select * from MID.ZFBH_CASE_XS_lajds@zfbh_sop t where t.isdel = '0' ) p
ON (k.id = p.id)
WHEN MATCHED THEN
  update
     set ISDEL       = p.ISDEL,
         DATAVERSION = p.DATAVERSION,
         LRR_SFZH    = p.LRR_SFZH,
         LRSJ        = p.LRSJ,
         XGR_SFZH    = p.XGR_SFZH,
         XGSJ        = p.XGSJ,
         WSZT        = p.WSZT,
         CBQY_BH     = p.CBQY_BH,
         AJBH        = p.AJBH,
         CBDW_BH     = p.CBDW_BH,
         CBDW_MC     = p.CBDW_MC,
         CBDW_JC     = p.CBDW_JC,
         CBR_SFZH    = p.CBR_SFZH,
         CBR_XM      = p.CBR_XM,
         TFSJ        = p.TFSJ,
         WSH         = p.WSH,
         AJMC        = p.AJMC,
         RYBH        = p.RYBH,
         RYXM        = p.RYXM,
         XYRXB       = p.XYRXB,
         XYRCSRQ     = p.XYRCSRQ,
         XYRZZ       = p.XYRZZ,
         XYRDWZY     = p.XYRDWZY,
         PZR_SFZH    = p.PZR_SFZH,
         PZR_XM      = p.PZR_XM,
         PZSJ        = p.PZSJ,
         FLTK        = p.FLTK,
         TFR_XM      = p.TFR_XM,
         TFR_SFZH    = p.TFR_SFZH,
         SIGNNAME    = p.PSIGNNAME,
         PSIGNNAME   = p.PSIGNNAME,
         YWID        = p.YWID,
         RKSJ        = p.RKSJ,
         MODIFTIME   = p.XGSJ
   where MODIFTIME < p.XGSJ
WHEN NOT MATCHED THEN
  insert
    (ID,
     ISDEL,
     DATAVERSION,
     LRR_SFZH,
     LRSJ,
     XGR_SFZH,
     XGSJ,
     WSZT,
     CBQY_BH,
     AJBH,
     CBDW_BH,
     CBDW_MC,
     CBDW_JC,
     CBR_SFZH,
     CBR_XM,
     TFSJ,
     WSH,
     AJMC,
     RYBH,
     RYXM,
     XYRXB,
     XYRCSRQ,
     XYRZZ,
     XYRDWZY,
     PZR_SFZH,
     PZR_XM,
     PZSJ,
     FLTK,
     TFR_XM,
     TFR_SFZH,
     SIGNNAME,
     PSIGNNAME,
     YWID,
     RKSJ,
     MODIFTIME)
  values
    (p.ID,
     p.ISDEL,
     p.DATAVERSION,
     p.LRR_SFZH,
     p.LRSJ,
     p.XGR_SFZH,
     p.XGSJ,
     p.WSZT,
     p.CBQY_BH,
     p.AJBH,
     p.CBDW_BH,
     p.CBDW_MC,
     p.CBDW_JC,
     p.CBR_SFZH,
     p.CBR_XM,
     p.TFSJ,
     p.WSH,
     p.AJMC,
     p.RYBH,
     p.RYXM,
     p.XYRXB,
     p.XYRCSRQ,
     p.XYRZZ,
     p.XYRDWZY,
     p.PZR_SFZH,
     p.PZR_XM,
     p.PZSJ,
     p.FLTK,
     p.TFR_XM,
     p.TFR_SFZH,
     p.SIGNNAME,
     p.PSIGNNAME,
     p.YWID,
     p.RKSJ,
     p.XGSJ);
commit;

MERGE INTO sop_sadjb k
USING (select * from MID.ZFBH_CASE_XZ_sadjb@zfbh_sop t where t.isdel = '0') p
ON (k.id = p.id)
WHEN MATCHED THEN
  update
     set ISDEL       = p.ISDEL,
         DATAVERSION = p.DATAVERSION,
         LRR_SFZH    = p.LRR_SFZH,
         LRSJ        = p.LRSJ,
         XGR_SFZH    = p.XGR_SFZH,
         XGSJ        = p.XGSJ,
         WSZT        = p.WSZT,
         CBQY_BH     = p.CBQY_BH,
         AJBH        = p.AJBH,
         CBDW_BH     = p.CBDW_BH,
         CBDW_MC     = p.CBDW_MC,
         CBDW_JC     = p.CBDW_JC,
         CBR_SFZH    = p.CBR_SFZH,
         CBR_XM      = p.CBR_XM,
         AYBH        = p.AYBH,
         AYMC        = p.AYMC,
         AJMC        = p.AJMC,
         AJLY        = p.AJLY,
         SLSJ        = p.SLSJ,
         BAR_XM      = p.BAR_XM,
         BAR_XB      = p.BAR_XB,
         BAR_CSRQ    = p.BAR_CSRQ,
         BAR_DW      = p.BAR_DW,
         BAR_LXFS    = p.BAR_LXFS,
         BAR_ZZ      = p.BAR_ZZ,
         BAR_ZJZL    = p.BAR_ZJZL,
         BAR_ZJHM    = p.BAR_ZJHM,
         BASJ        = p.BASJ,
         YSDW        = p.YSDW,
         YSRXM       = p.YSRXM,
         YSDWLXDH    = p.YSDWLXDH,
         JYAQ        = p.JYAQ,
         YSDWMC      = p.YSDWMC,
         YSR         = p.YSR,
         SLYJ        = p.SLYJ,
         WSH         = p.WSH,
         JQBH        = p.Jqbh,
         JBR         = p.JBR,
         JBRXM       = p.JBRXM,
         JBDD        = p.JBDD,
         SWDW        = p.SWDW,
         SAYJ1       = p.SAYJ1,
         SAYJ2       = p.SAYJ2,
         SAYJ3       = p.SAYJ3,
         SAYJ4       = p.SAYJ4,
         SAYJ5       = p.SAYJ5,
         QT          = p.QT,
         SFJSZJ      = p.SFJSZJ,
         FASJ        = p.FASJ,
         SAYJ        = p.SAYJ,
         SIGNNAME    = p.SIGNNAME,
         GLZJQDID    = p.GLZJQDID,
         ISYTZJQD    = p.ISYTZJQD,
         LRR_XM      = p.LRR_XM,
         FADD        = p.FADD,
         ZBDWJZ      = p.ZBDWJZ,
         PSIGNNAME   = p.PSIGNNAME,
         SWDWBH      = p.SWDWBH,
         RKSJ        = p.Rksj
   where MODIFTIME < p.xgsj
WHEN NOT MATCHED THEN
  insert
    (ID,
     ISDEL,
     DATAVERSION,
     LRR_SFZH,
     LRSJ,
     XGR_SFZH,
     XGSJ,
     WSZT,
     CBQY_BH,
     AJBH,
     CBDW_BH,
     CBDW_MC,
     CBDW_JC,
     CBR_SFZH,
     CBR_XM,
     AYBH,
     AYMC,
     AJMC,
     AJLY,
     SLSJ,
     BAR_XM,
     BAR_XB,
     BAR_CSRQ,
     BAR_DW,
     BAR_LXFS,
     BAR_ZZ,
     BAR_ZJZL,
     BAR_ZJHM,
     BASJ,
     YSDW,
     YSRXM,
     YSDWLXDH,
     JYAQ,
     YSDWMC,
     YSR,
     SLYJ,
     WSH,
     JQBH,
     JBR,
     JBRXM,
     JBDD,
     SWDW,
     SAYJ1,
     SAYJ2,
     SAYJ3,
     SAYJ4,
     SAYJ5,
     QT,
     SFJSZJ,
     FASJ,
     SAYJ,
     SIGNNAME,
     GLZJQDID,
     ISYTZJQD,
     LRR_XM,
     FADD,
     ZBDWJZ,
     PSIGNNAME,
     SWDWBH,
     RKSJ,
     MODIFTIME)
  values
    (p.ID,
     p.ISDEL,
     p.DATAVERSION,
     p.LRR_SFZH,
     p.LRSJ,
     p.XGR_SFZH,
     p.XGSJ,
     p.WSZT,
     p.CBQY_BH,
     p.AJBH,
     p.CBDW_BH,
     p.CBDW_MC,
     p.CBDW_JC,
     p.CBR_SFZH,
     p.CBR_XM,
     p.AYBH,
     p.AYMC,
     p.AJMC,
     p.AJLY,
     p.SLSJ,
     p.BAR_XM,
     p.BAR_XB,
     p.BAR_CSRQ,
     p.BAR_DW,
     p.BAR_LXFS,
     p.BAR_ZZ,
     p.BAR_ZJZL,
     p.BAR_ZJHM,
     p.BASJ,
     p.YSDW,
     p.YSRXM,
     p.YSDWLXDH,
     p.JYAQ,
     p.YSDWMC,
     p.YSR,
     p.SLYJ,
     p.WSH,
     p.JQBH,
     p.JBR,
     p.JBRXM,
     p.JBDD,
     p.SWDW,
     p.SAYJ1,
     p.SAYJ2,
     p.SAYJ3,
     p.SAYJ4,
     p.SAYJ5,
     p.QT,
     p.SFJSZJ,
     p.FASJ,
     p.SAYJ,
     p.SIGNNAME,
     p.GLZJQDID,
     p.ISYTZJQD,
     p.LRR_XM,
     p.FADD,
     p.ZBDWJZ,
     p.PSIGNNAME,
     p.SWDWBH,
     p.RKSJ,
     p.XGSJ);
commit;

END;
